### ISSUE TITLE
DOKS cluster creation timeout

### ISSUE THREAD

**Issue by mariusz-gomse-centra** [crossplane-contrib/provider-upjet-digitalocean#48]
I wanted to create very basic DOKS cluster with below manifest:
```
apiVersion: kubernetes.digitalocean.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: kubernetes/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    name: foo
    nodePool:
      - name: worker-pool
        nodeCount: 1
        size: s-2vcpu-2gb
        taint:
          - effect: NoSchedule
            key: workloadKind
            value: database
    region: ams3
    version: 1.32.1-do.0
  providerConfigRef:
    name: crossplane-provider-do
```

After 3 minutes in the CR event I got: `cannot apply: apply failed: `
And then next messages are like `cannot apply: apply failed: Error creating Kubernetes cluster: POST https://api.digitalocean.com/v2/kubernetes/clusters: 422 (request "...") a cluster with this name already exists: `

I guess that the problem is static timeout set to 3 minutes [here](https://github.com/crossplane-contrib/provider-upjet-digitalocean/blob/main/internal/controller/kubernetes/cluster/zz_controller.go#L42) and that DO is creating DOKS cluster in 6/7 minutes... (at least in my case)

So probably the easiest solution will be just to put higher timeout (10 minutes?) but maybe it is possible to have this timeout configurable?
